# Generated by Django 5.2.4 on 2025-08-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('f_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('product', models.CharField(max_length=1)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
